global:
  scrape_interval: 60s
  evaluation_interval: 60s

scrape_configs:
  - job_name: "amazon_price_tracker"
    static_configs:
      - targets: ["scraper:8000"]
    scrape_interval: 60s
    scrape_timeout: 30s
