apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: DS_POSTGRES
    access: proxy
    url: postgres:5432
    database: mlb_stats
    user: mlb
    isDefault: true
    editable: false
    secureJsonData:
      password: mlbpass
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
